function [methodinfo,structs,enuminfo,ThunkLibName]=MatlabNetComClient3_x64_proto
%MATLABNETCOMCLIENT3_X64_PROTO Create structures to define interfaces found in 'MatlabNetComClient'.

%This function was generated by loadlibrary.m parser version 1.1.6.34 on Wed Sep 21 08:55:36 2016
ival={cell(1,0)}; % change 0 to the actual number of functions to preallocate the data.
structs=[];enuminfo=[];fcnNum=1;
fcns=struct('name',ival,'calltype',ival,'LHS',ival,'RHS',ival,'alias',ival,'thunkname', ival);
MfilePath=fileparts(mfilename('fullpath'));
ThunkLibName=fullfile(MfilePath,'MatlabNetComClient3_x64_thunk_pcwin64');
%  int ConnectToServer ( const char * serverName ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='ConnectToServer'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  int DisconnectFromServer (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='DisconnectFromServer'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  char * GetClientVersionString (); 
fcns.thunkname{fcnNum}='cstringThunk';fcns.name{fcnNum}='GetClientVersionString'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int OpenStream ( const char * objectName ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='OpenStream'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  int CloseStream ( const char * objectName ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='CloseStream'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  int SendCommand ( const char * command , char ** reply , int * numBytesAvailable ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrThunk';fcns.name{fcnNum}='SendCommand'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'stringPtrPtr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int SetApplicationName ( const char * myApplicationName ); 
fcns.thunkname{fcnNum}='int32cstringThunk';fcns.name{fcnNum}='SetApplicationName'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring'};fcnNum=fcnNum+1;
%  int GetDASObjectsAndTypes ( char ** objectNames , char ** typeNames , int * pNumBytesPerString , int * pNumStrings ); 
fcns.thunkname{fcnNum}='int32voidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetDASObjectsAndTypes'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'stringPtrPtr', 'stringPtrPtr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  char * GetServerPCName (); 
fcns.thunkname{fcnNum}='cstringThunk';fcns.name{fcnNum}='GetServerPCName'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  char * GetServerIPAddress (); 
fcns.thunkname{fcnNum}='cstringThunk';fcns.name{fcnNum}='GetServerIPAddress'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  char * GetServerApplicationName (); 
fcns.thunkname{fcnNum}='cstringThunk';fcns.name{fcnNum}='GetServerApplicationName'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='cstring'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int AreWeConnected (); 
fcns.thunkname{fcnNum}='int32Thunk';fcns.name{fcnNum}='AreWeConnected'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int GetRecordBufferSize ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='GetRecordBufferSize'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int SetRecordBufferSize ( int numRecordsToBuffer ); 
fcns.thunkname{fcnNum}='int32int32Thunk';fcns.name{fcnNum}='SetRecordBufferSize'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'int32'};fcnNum=fcnNum+1;
%  int GetMaxCSCSamples ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='GetMaxCSCSamples'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int GetSpikeSampleWindowSize ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='GetSpikeSampleWindowSize'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int GetMaxSpikeFeatures ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='GetMaxSpikeFeatures'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int GetMaxEventStringLength ( void ); 
fcns.thunkname{fcnNum}='int32voidThunk';fcns.name{fcnNum}='GetMaxEventStringLength'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}=[];fcnNum=fcnNum+1;
%  int GetNewCSCData ( const char * acqEntName , __int64 * timeStamps , int * channelNumbers , int * samplingFrequency , int * numValidSamples , short * samples , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewCSCData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr', 'int16Ptr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int GetNewSEData ( const char * acqEntName , __int64 * timeStamps , int * scNumbers , int * cellNumbers , int * featureValues , short * samples , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewSEData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr', 'int16Ptr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int GetNewSTData ( const char * acqEntName , __int64 * timeStamps , int * scNumbers , int * cellNumbers , int * featureValues , short * samples , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewSTData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr', 'int16Ptr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int GetNewTTData ( const char * acqEntName , __int64 * timeStamps , int * scNumbers , int * cellNumbers , int * featureValues , short * samples , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewTTData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr', 'int16Ptr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int GetNewEventData ( const char * acqEntName , __int64 * timeStamps , int * eventIDs , int * ttlValues , char ** eventStrings , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewEventData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'stringPtrPtr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
%  int GetNewVTData ( const char * acqEntName , __int64 * timeStamps , int * extractedLocations , int * extractedAngles , int * numRecordsReturned , int * numDroppedRecords ); 
fcns.thunkname{fcnNum}='int32cstringvoidPtrvoidPtrvoidPtrvoidPtrvoidPtrThunk';fcns.name{fcnNum}='GetNewVTData'; fcns.calltype{fcnNum}='Thunk'; fcns.LHS{fcnNum}='int32'; fcns.RHS{fcnNum}={'cstring', 'int64Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr', 'int32Ptr'};fcnNum=fcnNum+1;
methodinfo=fcns;